/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bunny.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bunny.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.1, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.64}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.008']} position={[0.02, 1.05, 0.04]} scale={[0.56, 0.6, 0.55]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.009']} position={[0.02, 1.05, 0]} scale={[0.62, 0.67, 0.61]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.007']} position={[0.02, 2.3, 0]} scale={[1.17, 0.91, 1]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.003']} position={[0.02, 0.13, 0]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.002']} position={[0.02, 0.13, 0]} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.bunny_texturee} position={[0.02, 2.3, 0.01]} scale={[1.17, 0.91, 0.94]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.001']} position={[0.02, 0, 0]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.010']} position={[0.02, 2.3, -0.02]} rotation={[0.12, 0, 0]} scale={[1.17, 0.91, 0.94]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Material.007']} position={[0.02, 2.16, 0.87]} rotation={[-0.34, 0, 0]} scale={0.08} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.008']} position={[0.02, 1, -0.57]} scale={0.22} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bunny.gltf')
