/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 penguin.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/penguin.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Roundcube.geometry} material={materials['Material.004']} position={[0, 1.44, -0.05]} scale={1.19} />
      <mesh geometry={nodes.Roundcube001.geometry} material={materials['Material.004']} position={[0, -0.18, -0.05]} scale={1.19} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.004']} position={[0, 2.31, 1.64]} scale={1.19} />
      <mesh geometry={nodes.Roundcube002.geometry} material={materials['Material.004']} position={[0, -0.18, -0.05]} scale={1.19} />
      <mesh geometry={nodes.Roundcube003.geometry} material={materials['Material.004']} position={[0, 1.44, -0.05]} scale={1.19} />
      <mesh geometry={nodes.Roundcube004.geometry} material={materials['Material.004']} position={[0, 1.44, -0.05]} scale={1.19} />
      <mesh geometry={nodes.Roundcube005.geometry} material={materials['Material.004']} position={[0, -0.18, -0.05]} scale={1.19} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[0, 2.31, 1.64]} scale={1.19} />
      <mesh geometry={nodes.Roundcube006.geometry} material={materials['Material.004']} position={[0, -0.18, -0.05]} scale={1.19} />
      <mesh geometry={nodes.Roundcube007.geometry} material={materials['Material.004']} position={[0, 1.44, -0.05]} scale={1.19} />
    </group>
  )
}

useGLTF.preload('/penguin.gltf')
