/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 raccoon.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/raccoon.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ears_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} rotation={[Math.PI / 9, 0, 0]} />
      <mesh geometry={nodes.Tail_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
      <mesh geometry={nodes.Head_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} rotation={[Math.PI / 9, 0, 0]} />
      <mesh geometry={nodes.Suit_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
      <mesh geometry={nodes.TieKnot_low.geometry} material={materials.M_Raccoon} position={[0, 1.02, 0.13]} rotation={[-0.75, 0, 0]} />
      <mesh geometry={nodes.TieTail_low.geometry} material={materials.M_Raccoon} position={[0, 1, 0.15]} rotation={[-0.42, 0, 3.13]} />
      <mesh geometry={nodes.Shirt_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
      <mesh geometry={nodes.Pot_low.geometry} material={materials.M_Raccoon} position={[-0.2, 2.19, -0.1]} rotation={[-0.28, -0.07, 0.3]} />
      <mesh geometry={nodes.PiceOfDirt_low.geometry} material={materials.M_Raccoon} position={[0.19, 1.87, 0.06]} rotation={[0.62, 0.31, -0.07]} />
      <mesh geometry={nodes.SuitButton_low.geometry} material={materials.M_Raccoon} position={[0.04, 0.84, 0.25]} rotation={[-1.95, -0.15, -2.78]} />
      <mesh geometry={nodes.ButtonStich1_low.geometry} material={materials.M_Raccoon} position={[0.05, 0.85, 0.26]} rotation={[0.88, -0.58, -0.43]} />
      <mesh geometry={nodes.ButtonStich2_low.geometry} material={materials.M_Raccoon} rotation={[-1.56, -0.87, -2.57]} />
      <mesh geometry={nodes.Body_low.geometry} material={materials.M_Raccoon} position={[0, 1.06, -0.13]} />
    </group>
  )
}

useGLTF.preload('/raccoon.gltf')
